### PR TITLE
[BD-14] [SE-3241] Scaffold and create initial unit tests with helpers.

### PR DESCRIPTION
**Pull request by Kelketek**
This pull request creates an initial set of unit tests and helper functions that were created in the process of creating them, as well as a handful of improvements that were found while testing. For easier review, a copy of this PR is available at https://github.com/open-craft/frontend-app-library-authoring/pull/3

**Dependencies**: https://github.com/edx/frontend-app-library-authoring/pull/9

**Merge deadline**: No specific due date, but sooner is better than later.

**Testing instructions**:

1. `npm install`
2. `npm run test`

**Author notes and concerns**:

This PR includes several functions that I believe will help make the tests more succinct. They're a little metaprogrammy but they make me happy. It also includes a set of factory functions that I hope will serve as a useful pattern to build from.

The tests are built for the Library Access section of the app because it is the one I've built and it uses the (container pattern)[https://www.freecodecamp.org/news/react-superpowers-container-pattern-20d664bdae65/], which I anticipated would make it fairly easy to test. So far, so good.

Because there is another PR for tests that is being worked on by @arbrandes during our current sprint at OpenCraft, I've elected to go ahead and put up this Pull Request before our second week begins in order that the infrastructure functions might be used for making more unit tests more effectively. The Library Access PR, thus, is not fully covered, but it can be with a follow-up PR later if desired.

**Reviewers**
- [ ] @mavidser
- [x] @kdmccormick

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @Kelketek! I've created [BLENDED-586](https://openedx.atlassian.net/browse/BLENDED-586) to keep track of it in Jira.   More details are on the [BD-14](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1545011241/BD-14+Blockstore+Powered+Content+Libraries+Taxonomies) project page.

When this pull request is ready, tag your edX technical lead.

**Review by mavidser — APPROVED** [review]
Reviewed in open-craft/frontend-app-library-authoring#3 - this should be good for your review now @kdmccormick.

**Review by kdmccormick — CHANGES_REQUESTED** [review]
Left a [review over here](https://github.com/open-craft/frontend-app-library-authoring/pull/3#pullrequestreview-490929849).

**Review by kdmccormick — APPROVED** [review]
Looks good. Ping me when you're ready for a merge.

**Comment by Kelketek** [comment]
@kdmccormick This has been rebased and is ready for merge.

**Pull request merged**
