### PR TITLE
[BD-14] [SE-2945] Add pagination to library list view

### PR DESCRIPTION
**Pull request by gabor-boros**
Introduce pagination in the library list page so an unlimited number libraries can be listed. For the first iteration, we stick to a default limit of 20 items per page.

**Dependencies**:

* [Backend PR solving pagination for legacy libraries](https://github.com/edx/edx-platform/pull/25187)

**Screenshots**:

Screen-Recording

_for demo purposes, the recording shows a pagination where page size was 2_

**Merge deadline**: None

**Testing instructions**:

_Prerequisites: A running devstack for MFE_

0. Checkout the studio **[backend changes](https://github.com/edx/edx-platform/pull/25187)** 
1. Start all the required services
2. Open studio
3. Login with edx
4. Switch to libraries tab
5. Create 1 library -> the pagination will show up
6. Create at least 20 more libraries -> other pages can be selected

**Author notes and concerns**:

1. The `all` filter option was removed, hence we changed the default `all` to default `complex (beta)`. The reasoning behind this: managing the merge of 2 paginated response and being able to provide a consistent user experience would be near impossible without hacking and/or sending more than required amount of requests
2. `enzyme` package was added, due to we need mounting to be able to test pagination. Without enzyme's mount, the pagination will not render properly and the paginator will not work. (by the way, paragon's tests are using enzyme, I think for the same reason - this may relate to the component will receive props deprecation warning)

**Reviewers**
- [x] @arbrandes 
- [ ] edX reviewer[s] TBD

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @gabor-boros! I've created [OSPR-5024](https://openedx.atlassian.net/browse/OSPR-5024) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Review by arbrandes — APPROVED** [review]
@gabor-boros, great work here, as well.  :+1:

- [x] I tested this as instructed
- [x] I read through the code
- [x] I checked for accessibility issues: pagination works via keyboard shortcuts
- [x] Includes sufficient inline documentation

**Comment by natabene** [comment]
@gabor-boros Thank you for your contribution. Please let me know once this is ready for our review.

**Comment by gabor-boros** [comment]
@natabene Thank you! It is ready 😊

**Comment by natabene** [comment]
@marcotuts Do you want to review?

**Comment by marcotuts** [comment]
Added BD-14 to this, thanks! ok to move to engineering

**Comment by kdmccormick** [comment]
_Thanks for your work so far on this. We're pausing development and code review on BD-14 for now to allow more planning and design to be done before work is resumed on Milestone 3. Until then, edX most likely won't be able to review this PR._

**Comment by edx-webhook** [comment]
Hello @gabor-boros: We are unable to continue with review of your submission at this time. Please see the associated JIRA ticket for more explanation.

**Comment by kdmccormick** [comment]
Sorry, I think this was closed mistakenly.

**Comment by gabor-boros** [comment]
@kdmccormick No problems at all. Would this work be continued on BD related tickets? In other words: Should I resolve conflicts here?

**Comment by gabor-boros** [comment]
Closed in favor of https://github.com/edx/frontend-app-library-authoring/pull/23

**Pull request closed without merging**
