### PR TITLE
Add MathJax support

### PR DESCRIPTION
**Pull request by arbrandes**
Adds support for rendering MathJax, which in the LMS and Studio is done globally.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @arbrandes! I've created [OSPR-5929](https://openedx.atlassian.net/browse/OSPR-5929) to keep track of it in JIRA.

As a core committer in this repo, you can merge this once the pull request is approved per the [core committer reviewer requirements](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1529675973/Open+edX+Core+Committers#Reviews-and-Ownership) and according to the agreement with your edX Champion.

**Comment by natabene** [comment]
@arbrandes Thank you for your contribution. Please let me know once it is ready for our review.

**Comment by arbrandes** [comment]
@natabene it's ready. :)

This would be up @marcotuts' or @kdmccormick's alley, but I could be wrong.

**Comment by arbrandes** [comment]
Trying @davidjoy here as well.  Any objections?  This has been extensively tested.

(It builds on this ugly shim, but until all XBlocks become fully self-contained, there's no other way.)

**Comment by davidjoy** [comment]
@arbrandes I don't have a lot of context here and would defer to @kdmccormick.  

Is this so that XBlocks in the library authoring MFE can use MathJax in-context, basically?

**Comment by arbrandes** [comment]
@davidjoy, yes, exactly.  This is something that is implemented globally in several places in the LMS and Studio (see [here](https://github.com/edx/edx-platform/blob/master/lms/templates/courseware/courseware.html#L81) and [here](https://github.com/edx/edx-platform/blob/master/common/templates/mathjax_include.html), for example).

**Review by davidjoy — APPROVED** [review]
:shipit: Looking for some review from T&L, but it sounds like this can move forward.

**Comment by arbrandes** [comment]
Thanks @davidjoy!  Since this is pretty straightforward, I'm going to go ahead and merge it.

**Comment by edx-webhook** [comment]
@nedbat, @stvstnfrd: thought you might like to know that arbrandes merged this pull request.

**Pull request merged**
