### PR TITLE
[BD-14] Implement basic authoring

### PR DESCRIPTION
**Pull request by arbrandes**
### Description

Implement basic authoring
    
Adds a first version of library authoring functionality, including the ability to add, view, and edit blocks.
    
This is a straight port of equivalent features in [ramshackle](https://github.com/open-craft/ramshackle), and is meant as a basis for iteration in the near future.  Notably:

* The layout and flow is experimental.
* There is little in the way of theming and i18n.
* As with ramshackle itself, editing certain block types does not work.

### Manual Testing

To test this manually in a devstack, proceed as follows:

1. Check out the latest devstack master and `make dev.clone`.

1.  Check out this PR's branch (`arbrandes/authoring-v1`) in `frontend-app-library-authoring`.

1. Launch the master devstack as usual.

1. Launch `frontend-app-library-authoring` via `make dev.up.frontend-app-library-authoring`, since it is not a default service.

1. Checkout out [blockstore](https://github.com/edx/blockstore/), `make dev.up` and `make dev.provision` it.  In `make blockstore-shell`, create an auth token for edx-platform and a new collection, making a note of its UUID:

    ```bash
    echo "from django.contrib.auth import get_user_model; from rest_framework.authtoken.models import Token; User = get_user_model(); edxapp_user, _ = User.objects.get_or_create(username='edxapp'); Token.objects.get_or_create(user=edxapp_user, key='edxapp-insecure-devstack-key')" | ./manage.py shell
    ./manage.py createcollection "Studio Collection"
    Created Collection: 36aefd6a-c39e-4ede-ab48-fe40ddecfb33 (Studio Collection)
    ```

1. Start blockstore with `make easyserver`.

1. Edit `frontend-app-library-authoring/.env.development` and add the UUID you obtained above to BLOCKSTORE_COLLECTION_UUID:

    ```bash
    BLOCKSTORE_COLLECTION_UUID=36aefd6a-c39e-4ede-ab48-fe40ddecfb33
    ```

1. Restart the `frontend-app-library-authoring` container:

    ```bash
    cd devstack
    docker-compose restart frontend-app-library-authoring
    ```

1. In the Studio shell, configure it with blockstore credentials and enable the `ENABLE_LIBRARY_AUTHORING_MICROFRONTEND` feature flag:

    ```bash
    make studio-shell
    echo "BLOCKSTORE_API_AUTH_TOKEN = 'edxapp-insecure-devstack-key'" >> /edx/app/edxapp/edx-platform/cms/envs/private.py
    echo "BLOCKSTORE_API_AUTH_TOKEN = 'edxapp-insecure-devstack-key'" >> /edx/app/edxapp/edx-platform/lms/envs/private.py
    vim /edx/etc/studio.yml
    ---
    FEATURES:
        ENABLE_LIBRARY_AUTHORING_MICROFRONTEND: true
    ```

1. Exit the shell and restart Studio:

    ```bash
    make studio-restart
    ```

1. In the browser, go to http://localhost:18010/admin/organizations/organization/add/, log in as `edx`, and create an organization named (and short-named)`edX`.

1. Finally, create a `studio.library_authoring_mfe` waffle flag via http://localhost:18010/admin/waffle/flag/, and enable it for everyone.

1. Now go to Studio Home (http://localhost:18010/home/) and click on the Libraries tab.

    <details>
    <summary>Screenshot</summary>

    Screenshot_2020-07-10_21-27-08
    </details>

1. You should be taken to the MFE as a logged-in user and presented with an empty page.  (If, on the other hand, there are previously existing libraries, they'll be shown here).

1. Click on `New Library` in the upper right.  You should see the form appear.

    <details>
    <summary>Screenshot</summary>

    Screenshot_2020-07-10_21-35-13
    </details>

1. Create a new complex library by filling out the form with the "edX" organization and clicking `CREATE`.  You should be taken to the library detail page.  Check that in this new library, you can see the "Add New Component" form.

    <details>
    <summary>Screenshot</summary>

    Screenshot_2020-08-10_14-48-35
    </details>

1. Add a new poll block with a "poll1" slug.

    <details>
    <summary>Screenshot</summary>
    
    Screenshot_2020-08-10_14-51-27
    </details>

1. After clicking "Add Component", you should see the block on the screen, and the "Publish" button on the right should be enabled.

    <details>
    <summary>Screenshot</summary>
    
    Screenshot_2020-08-10_14-52-40
    </details>

1. Click on "Publish", on the right.  The "Unpublished Changes" badge on the block card should disappear, and the "Publish" button should be disabled.

    <details>
    <summary>Screenshot</summary>
    
    Screenshot_2020-08-10_14-55-43
    </details>

1. Click on the "View" button in the poll block card.  You should be taken to the block view page:

    <details>
    <summary>Screenshot</summary>
    
    Screenshot_2020-08-12_21-35-01
    </details>

1. Proceed to make changes to the block as you would on ramshackle.

    <details>
    <summary>Screenshot: edit tab</summary>

    Screenshot_2020-08-12_21-37-08
    </details>

    <details>
    <summary>Screenshot: assets tab</summary>
    
    Screenshot_2020-08-12_21-37-50
    </details>

    <details>
    <summary>Screenshot: source tab</summary>

    Screenshot_2020-08-12_21-38-50
    </details>

    <details>
    <summary>Screenshot: learn tab</summary>

    Screenshot_2020-08-12_21-39-23
    </details>

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @arbrandes! I've created [BLENDED-541](https://openedx.atlassian.net/browse/BLENDED-541) to keep track of it in Jira.   More details are on the [BD-14](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1545011241/BD-14+Blockstore+Powered+Content+Libraries+Taxonomies) project page.

When this pull request is ready, tag your edX technical lead.

**Comment by arbrandes** [comment]
@kdmccormick, since your context is fresh from reviewing #3, I'm submitting this one for your take while I work on addressing your previous comments.

As noted in the description above, this is not meant to represent the definitive authoring experience.  Rather, it is a port of (most of) what ramshackle does.  While we do intend for this to be merged, the idea is to use it as a basis for conversation about how to improve it iteratively.

**Comment by kdmccormick** [comment]
Thanks @arbrandes; I'm ack'ing this now, with the hope of giving it a look in the front half of the week.

**Comment by arbrandes** [comment]
Note to reviewers: I'm trying to reproduce the weird Travis build failure locally, but as of yet have been unsuccessful:

```
ERROR in ./src/index.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Cannot read property 'length' of undefined
    at /home/travis/build/edx/frontend-app-library-authoring/src/index.scss:9960:7
```

**Comment by arbrandes** [comment]
Build issue fixed via 965eebdf56ebc4369591e888c8f18c03620bda1f.

This brings to the forefront the main disadvantage of trying to use Studio CSS as-is.  It's too cumbersome.  I started doing it to try and save time, but it's quickly becoming a time _sink_.

For future PRs I'm going to avoid importing any more Studio CSS, and instead will start building a paragon/bootstrap-based, functional-CSS equivalent.  It's probably not going to look _exactly_ the same, but it'll save on a lot of headaches in the future.

@kdmccormick, do you happen to know what the folks over at the course-authoring MFE intend to do about this, if anything?

**Comment by kdmccormick** [comment]
@arbrandes It looks like the folks working on the course authoring MFE are not even trying to match the styling of Studio. That being said, they are only replacing a single page of Studio.

@marcotuts Can you shed light whether it's important (and if so, how important) it is for the library authoring MFE to look and feel like Studio?

**Comment by marcotuts** [comment]
We should seek to emulate the studio patterns in particular when they come to component editing, the general page layout (title, heading, primary right actions for component creation, etc.) I can provide more details wireframes wherever is helpful beyond what was in the project discovery documents. The Page & Resources view being built as part of the discussions project was originally built out to emulate the blue wireframe pattern / styling, but eventually that blue tinge will go away and the idea is to mostly follow page headings and styles for now. 

From my recollection of ramshackle the patterns it had were not close to Studio's so it would take some effort to emulate this. Ideally we are able to do so in clean / simple base react or paragon components wherever possible. It may make sense to set this as an agenda topic to discuss in more detail. For now I will raise this with our UX T&L team members so that we can turn our attention to this ASAP after discussions work in flight to support a clear picture on where we would like this to go from a styling perspective. Thanks for flagging!

**Comment by arbrandes** [comment]
@marcotuts, sounds like we're on the same page, then.  I intend to keep as close as possible to the Studio UI experience, but contrary to what I've been doing here so far, I won't continue trying to import Studio CSS verbatim.

**Comment by kdmccormick** [comment]
Some high-level feedback:
* I really like the idea of merging in this port of Ramshackle ASAP. It's a good starting point and should make testing, development, and feedback easier for everyone. Thank you for putting this together.
* It's unclear to me what kind of component editing experience we want to generate from this project (BD-14) and whether or not it (a) needs to mirror that of current Studio, (b) needs to set a good direction that we expect the course-authoring MFE eventually will follow, or (c) neither. This is at the top of my mind for issues to discuss Monday. For that reason I'm purposely going to generally refrain from commenting on the details of the component editing UX, and am happy to adopt Ramshackle's pattern until we have made that call.
* There's a lot of code here! Would you like a line-by-line review from edX, or do you think someone from OpenCraft would be best suited to look at this?

Some specific issues I noticed upon first pass-through:
* Trying to edit an HTML block, I see the following exception from studio: https://gist.github.com/kdmccormick/03d9c10e763adfaa06cef1f10ea3492d
* Trying to edit a Poll block, I the contents of the previously-used tab sometimes "stick around"; for example, if I got from "Edit" to "View" and back to "Edit", I still see the "View" version of the block.
* When I switch between View/Edit/Assets/etc., it seems like the entire page body re-renders, which is a little jarring. Given what I said about uncertainty of the editing UX, though, don't consider this blocking for this PR.

**Comment by arbrandes** [comment]
@kdmccormick, thanks for testing!  Yes, the intention here is mostly to provide a working basis for future discussion and development.

ACK on the bugs.  Here's what I indent to do:

* The "fix" for some of the non-working blocks will simply be to disable the ability to edit them using the Studio view.  I'll do that as part of this PR.  (This was actually foreseen.  We'll need to work separately on modifying each Studio view so that it works with the MFE.  We've already scheduled tasks to do so for the CAPA problems and videos.)
* Yes, on further testing I did notice that the block HTML sometimes doesn't update correctly.  Don't know what's causing it, but I'll try and fix it before requesting a merge.
* The full page reload was just me being a little lazy. :)  But yes, only because I know this is supposed to be temporary UX.  In any case, I'll try and fit in a properly contained spinner while fixing the first item above, before Monday.  I'll also see about not polluting history with each tab.

As for a line-by-line review, don't sweat it, I'm going to lean on @bradenmacdonald and/or @mavidser. ;)

**Comment by kdmccormick** [comment]
@arbrandes Great!

As a general statement for this PR and any other PRs against this repo while it's in its early stages: I am fine on punting bugs or UX hacks to future PRs, trusting that you folks are cataloging them as we go. Really, I'd just like to avoid merging in issues that we're unaware of. So please don't feel like you need to fix everything I mention in order to get this merged, especially if it's part of a component that might get completely reworked anyway!

**Comment by bradenmacdonald** [comment]
>  I am fine on punting bugs or UX hacks to future PRs, trusting that you folks are cataloging them as we go.

Adding on to that: please ensure there is either a Jira ticket, a GitHub issue, or a "known issues" line in the README file to track known bugs in a shared written form. I'd suggest the README file, so they can be tracked and updated along with each PR that creates/fixes them.

**Comment by kdmccormick** [comment]
@bradenmacdonald +1 to the README (or other RST file) idea for light-weight way of tracking these issues in a place we can both see.

**Comment by arbrandes** [comment]
@kdmccormick, I've fixed the specific issues you noted earlier, and added a "Known Issues" section to the README (cc @bradenmacdonald).  I agree that the latter is probably the least cumbersome way we have of maintaining a public TODO list.

If you have no objections, and since nobody else raised them, this is good to merge.

**Pull request merged**
