### PR TITLE
[BD-14] SE-2931 user access configuration

### PR DESCRIPTION
**Pull request by Kelketek**
This PR adds the ability to manage user permissions for librariesv2. It is dependent on https://github.com/edx/frontend-app-library-authoring/pull/7 For reviewing convenience, a version of this PR that only contains the relevant changes is available here: https://github.com/open-craft/frontend-app-library-authoring/pull/2

**Discussions**: https://docs.google.com/document/d/1hRrSmWWlGHhi-bh9AIlpSuLtJFnn2GpavNe8OQxthbE/edit

**Dependencies**: https://github.com/edx/frontend-app-library-authoring/pull/7

**Screenshots**: 
Screen Shot 2020-09-04 at 10 42 20 AM
Screen Shot 2020-09-04 at 10 42 41 AM
Screen Shot 2020-09-04 at 10 42 57 AM

**Merge deadline**: No hard deadline, but sooner is better than later.

**Testing instructions**:

1. Use the `edx-platform` branch `open-craft:fox/se-2931-user-access-adjustments` on the backend.
1. Follow the directions in https://github.com/edx/frontend-app-library-authoring/pull/4 up until item 15.
1. Create a new library of the 'complex' type.
1. In the top menu, there should be a 'User Access' link. Click it to visit the user access page.
1. Create and remove users, elevate their access, and depriv them. Verify the form resets upon add and that the user is added to the list.
1. Put bogus users and data into the email field to verify errors are handled well.
1. Delete users. Note, you should be able to delete yourself as a staff member, and still readd yourself, despite not having labeled privileges.
1. Verify that the interface does not let you remove or depriv yourself if there is no secondary admin.
1. Elevate a user who is not marked is_staff or is_superuser to 'staff' within the interface (that is, library author-- not marking them is_staff in the admin), and have them log in. Verify that the access control buttons are not present.

**Author notes and concerns**:

1. This is the largest amount of React code I've had to make so far, and the first time I've done real full component dev-- previously I modified other components. This is also my first time with Redux. I'd like feedback on how well I'm using those tools.
2. This task initially had an implementation similar to other pages currently in the repository. However, after speaking with @bradenmacdonald , he suggested using [the container pattern](https://www.freecodecamp.org/news/react-superpowers-container-pattern-20d664bdae65/) so that unit tests may be more easily written next sprint. This is my first time using this pattern and so I'd like his review to make sure I'm using/understanding it well.
3. It's been a while since I've done anything a11y related-- we're using paragon, which I believe is able to automate much of it, but I'd like to make sure I understand if I'm assuming its capabilities to be greater than they are in the code I'm writing, since I haven't immediately thought of any markup I'd have to customize here.

**Reviewers**
- [ ] @mavidser 
- [x] @bradenmacdonald 
- [x] @kdmccormick

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @Kelketek! I've created [OSPR-4947](https://openedx.atlassian.net/browse/OSPR-4947) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

Please let us know once your PR is ready for our review and all tests are green.

**Comment by mavidser** [comment]
@Kelketek I have only completed a usability review of the app, and can come back for a round of code review once #7 is merged. Does that sound okay?

Points from the test:
- Validating that at least one admin remains should be done on the server too.
- I was able to remove all admins by adding another user as admin, and then deleting my access. The delete button still remained for the other user which allowed the library to be admin-less.
- When logged in as a user with staff access, the page and action buttons are all visible, but everything returns a 403 error. We should remove all the buttons (or disable the page?) for such users.

Else, everything works as expected. The design looks especially great :)

**Comment by bradenmacdonald** [comment]
Read through the React code and added some comments at https://github.com/open-craft/frontend-app-library-authoring/pull/2

**Comment by kdmccormick** [comment]
As I mentioned on https://github.com/edx/edx-platform/pull/24919, I hope to take a first look at these two PRs tomorrow.

**Review by kdmccormick — CHANGES_REQUESTED** [review]
I left a [review on the open-craft fork PR](https://github.com/open-craft/frontend-app-library-authoring/pull/2#pullrequestreview-489085708).

**Review by kdmccormick — APPROVED** [review]
LGTM. Ping me when you want this merged.

**Review by mavidser — APPROVED** [review]
Small notes, else looks good to merge :+1:

- [x] I tested this: Testing instructions, permutations of access changes
- [x] I read through the code
- [x] I checked for accessibility issues
- [x] Includes documentation

**Comment by Kelketek** [comment]
@kdmccormick This is ready for merge.

**Pull request merged**
