### PR TITLE
[BD-14] SE-2946: Add support for Video and Problem library types.

### PR DESCRIPTION
**Pull request by Kelketek**
Adds support for library types, adding the 'video' and 'problem' type, and permitting filtering by these types.

**Discussions**: https://docs.google.com/document/d/1hRrSmWWlGHhi-bh9AIlpSuLtJFnn2GpavNe8OQxthbE/edit

**Dependencies**: https://github.com/edx/frontend-app-library-authoring/pull/7 must be merged first-- this PR includes the code from it. To review only the code from this PR, a convenience PR has been created here: https://github.com/open-craft/frontend-app-library-authoring/pull/1

**Screenshots**:

Creation page changes:

image

Edit Details:

image

Listing with filtering:

image

**Merge deadline**: "None" if there's no rush, "ASAP" if it's critical, or provide a specific date if there is one.

**Testing instructions**:

1. Use the `edx-platform` branch `open-craft:library_types` on the backend.
1. Follow the directions in https://github.com/edx/frontend-app-library-authoring/pull/4 up until item 15.
1. Create a new library of each type.
1. Create blocks in the library. In complex and legacy libraries, you should be able to create many different types.
1. In Video and problem libraries, you should be able to only create blocks of their respective type.
1. For complex, video, and problem libraries, test conversion by going to the Details menu for the library and switching the type.
    * This should succeed if the library is empty always.
    * It should succeed if moving from video or problem to complex.
    * It should succeed if moving from complex to problem, or complex to video, when all blocks match their respective types.
    * It should fail if moving from complex to problem, or problem to complex, if all blocks don't match the target type.
1. You should be able to filter the libraries by type on the library listing page. 

**Reviewers**
- [x] @yekibud 
- [x] @kdmccormick 
- [ ] @arbrandes (a11y)

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @Kelketek! I've created [BLENDED-567](https://openedx.atlassian.net/browse/BLENDED-567) to keep track of it in Jira.   More details are on the [BD-14](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1545011241/BD-14+Blockstore+Powered+Content+Libraries+Taxonomies) project page.

When this pull request is ready, tag your edX technical lead.

**Comment by yekibud** [comment]
:+1:

- [ ] I tested this: (describe what you tested)
- [ ] I read through the code
- [ ] I checked for accessibility issues
- [ ] Includes documentation
- [ ] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository

**Comment by kdmccormick** [comment]
Hi @Kelketek , now that #4 is merged, could you rebase in order to make review easier?

**Comment by Kelketek** [comment]
@kdmccormick My apologies-- I meant to write that https://github.com/edx/frontend-app-library-authoring/pull/7 must be merged first. You can also review just the parts that have changed by looking over this diff-only PR here: https://github.com/edx/frontend-app-library-authoring/

**Comment by kdmccormick** [comment]
Ah, now I see https://github.com/open-craft/frontend-app-library-authoring/pull/1. That PR will be helpful for review; thanks!

**Review by kdmccormick — APPROVED** [review]
Looks solid in general! Consider this PR approved from an architecture and design standpoint. As I mentioned in my email, I'll leave code review to you folks.

**Comment by kdmccormick** [comment]
Hi @Kelketek . This still looks good from my side. I see now that @yekibud gave a thumbs-up a while ago. Is this ready to merge?

**Comment by Kelketek** [comment]
@kdmccormick We're waiting on @arbrandes to give this an a11y lookover, as it wasn't done in the original review pass.

**Review by arbrandes — APPROVED** [review]
@Kelketek, @kdmccormick, this looks good to me, including a11y-wise  (I did find a11y issues _elsewhere_ though, and will be opening a PR this week with corresponding changes.).  :+1:

- [x] I tested this as instructed, and found no failures.
- [x] I read through the code
- [x] I checked for accessibility issues, and no problems are introduced here
- [x] Includes sufficient inline documentation

**Comment by kdmccormick** [comment]
@Kelketek Give me a ping when this is ready to go.

**Comment by Kelketek** [comment]
@kdmccormick Ready when you are :)

**Pull request merged**
