### PR TITLE
[BD-14] List filtering and library details

### PR DESCRIPTION
**Pull request by arbrandes**
#### Description

This introduces:

* Fixes for the remaining Paragon upgrade issues
* A fix for assets not showing immediately after being uploaded
* A header account dropdown menu that better matches Studio design
* Library list filtering
* Editing of library details

#### Manual testing

1. Follow the manual testing instructions in https://github.com/edx/frontend-app-library-authoring/pull/4 until step 16, so that you have a v2 library to work with.  Use this PR's branch (`arbrandes/filtering-and-details`), though.

1. If https://github.com/edx/edx-platform/pull/24510 hasn't been merged when testing this, check that PR out and restart Studio.  Otherwise, filtering won't work.

1. Make sure the `ORGANIZATIONS_APP` feature flag is set to `true` for Studio.  In the latest devstack, that is the default.  If unset, the org filter dropdown won't work.

1. In the library page of the library you just created, click on Settings > Details.

    <details>
    <summary>Screenshot</summary>

    Screenshot_2020-08-22_22-55-32
    </details>

1. Edit it as you see fit, then press submit.

    <details>
    <summary>Screenshot</summary>

    Screenshot_2020-08-22_23-02-59
    </details>

1. You will be taken back to the library page.  If you changed the title, you should see the new one here.

1. Go back to the library list, and create a few libraries.  Also create a second organization, and put some libraries in there.  Finally, use the filter fields on the right and check that the right libraries are being shown.

    <details>
    <summary>Screenshot</summary>

    Screenshot_2020-08-22_23-10-20
    </details>

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @arbrandes! I've created [BLENDED-553](https://openedx.atlassian.net/browse/BLENDED-553) to keep track of it in Jira.   More details are on the [BD-14](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1545011241/BD-14+Blockstore+Powered+Content+Libraries+Taxonomies) project page.

When this pull request is ready, tag your edX technical lead.

**Comment by bradenmacdonald** [comment]
@kdmccormick Will you be able to look at this this week? Ideally @arbrandes could address your feedback and merge this when he's back next Tuesday.

**Review by kdmccormick — APPROVED** [review]
Looks good. Some notes:

* The searching/filtering looks great!
* Certain searches in the library listing (for example "`(`") cause a 500 from Studio, which crashes the page. I will comment this on https://github.com/edx/edx-platform/pull/24510, as this is requires a backend fix. However, it reminds me that we'll need to handle Axios errors more gracefully in the MFE -- can you add it to the list of known issues?
* I've enabled `ORGANIZATIONS_APP` by default in Devstack. I'm going [to see about getting it enabled on edge.edx.org and by-default everywhere for Koa](https://openedx.atlassian.net/browse/TNL-7425).
* This PR moves the header in the direction that @marcotuts is envisioning. Don't feel like you need to address it in this PR, but we'll eventually want the header to look like this (my apologies if you've already seen these):

**Library Listing**
bd14_lo-fi_library-listing

**Library Editing**
bd14_lo-fi_library-authoring

These are lo-fi and still a WIP, but the idea is that the Courses/Libraries/Taxonomies tabs get pulled up into the header when in the listing view, and get replaced with the Content/Settings/etc. tabs when in the editing view. One of us (not sure if OpenCraft or edX) would need to make the corresponding change in old Studio as well.

**Comment by Kelketek** [comment]
@kdmccormick This is ready to be merged-- it has been approved internally and you've already given it arch review. I have rebased it to squash it down from 6 commits to three logical ones. If needed, I can squash further. Its backend dependency was also just merged. :)

**Comment by kdmccormick** [comment]
@Kelketek Sounds good, thanks! Logical commits are always cool with me.

**Pull request merged**
